use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AHFMAudioPlayerManager_Example' do
  pod 'AHFMAudioPlayerManager', :path => '../'

  target 'AHFMAudioPlayerManager_Tests' do
    inherit! :search_paths

    
  end
end
